### ISSUE TITLE
Modal is not shown in the child issue addition dialog

### ISSUE THREAD

**Issue by ashrafalzyoud** [sk-ys/redmine_enhanced_ux#71]
im using redmineup plugins 
when im added child issue and i need added new ( contact or company or deals )
the icon (+) its disable 
![Untitled](https://github.com/user-attachments/assets/f2fb5b44-aaef-4776-9776-01ca91e374ec)

**Comment by ashrafalzyoud** [comment]
?? @sk-ys

**Comment by sk-ys** [comment]
I don't have the redmineup CRM plugin Pro, so I can't reproduce the error.

**Comment by ashrafalzyoud** [comment]
Give me your email plz
To send u contact pro plz

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by sk-ys** [comment]
Thank you for your offer, but I must decline. Since the plugin you mentioned is a paid product, using it without purchasing my own copy could potentially violate its licensing terms. To ensure compliance with software licensing rules, I cannot use the plugin even if it were sent to me directly.

If you could provide more specific details about the issue, such as the steps to reproduce the problem or any relevant error messages in browser DevTools, it might help me investigate the compatibility without needing access to the paid plugin itself.

**Comment by ashrafalzyoud** [comment]
`<a id="issue_custom_field_values_9_add_link" tabindex="200" data-remote="true" data-method="get" href="/projects/ashraf-alzyoud/contacts/new?contact_field_name=issue%5Bcustom_field_values%5D%5B9%5D&amp;contacts_is_company=false" title="اضافة شركة جديدة"><img style="vertical-align: middle; margin-left: 5px;" src="/images/add.png?1722419408"></a>`

this link disabled

**Comment by ashrafalzyoud** [comment]
![fffffffffffffffffffff](https://github.com/user-attachments/assets/18be7d9a-2391-4c2a-8742-db18cef41120)
also added version or categoery  same error

**Comment by sk-ys** [comment]
@ashrafalzyoud
Thank you for your report. I have confirmed this error and attempted to fix it in the [issue-71](https://github.com/sk-ys/redmine_enhanced_ux/tree/issue-71) branch.
Please check it.

**Comment by ashrafalzyoud** [comment]
every things working now
u can colse this issue and merge it in main
